# NUMPY

In [1]:
import numpy as np

In [2]:
a = [x for x in range(1000)]

In [3]:
a

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [5]:
A = np.arange(1000, dtype=np.uint8)

In [6]:
A

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
B = np.arange(0,100,2)

In [8]:
B

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
my_arr = [[1,2,3,4],[4,5,5,4]]
np_arr = np.array(my_arr)

In [10]:
np_arr

array([[1, 2, 3, 4],
       [4, 5, 5, 4]])

In [11]:
type(np_arr)

numpy.ndarray

In [12]:
np_arr[0]

array([1, 2, 3, 4])

In [14]:
np_arr[:,1]

array([2, 5])

In [15]:
np_arr[:,1:]

array([[2, 3, 4],
       [5, 5, 4]])

In [16]:
np_arr[:,0]

array([1, 4])

In [17]:
np_arr[:,-1]

array([4, 4])

In [18]:
N = 16

In [19]:
D = np.random.rand(N,N).astype(np.float32)

In [20]:
D

array([[1.48127511e-01, 3.26609880e-01, 9.07437921e-01, 7.33720481e-01,
        7.30452657e-01, 1.75438449e-01, 9.49887395e-01, 2.74126858e-01,
        3.66282105e-01, 9.17316616e-01, 4.48354572e-01, 5.20365834e-01,
        4.02328908e-01, 8.09412897e-01, 5.42952538e-01, 9.36908722e-01],
       [1.12384045e-03, 1.95772171e-01, 2.90949672e-01, 8.76699448e-01,
        2.77706414e-01, 1.56914040e-01, 1.02598339e-01, 7.88447976e-01,
        8.12897265e-01, 7.87247241e-01, 6.25449419e-01, 2.28501260e-01,
        5.83108842e-01, 6.61231637e-01, 5.10919631e-01, 6.75715387e-01],
       [2.89098680e-01, 9.03928399e-01, 8.34610239e-02, 4.33001488e-01,
        7.76274979e-01, 8.54635596e-01, 4.96774137e-01, 7.00982332e-01,
        9.30824041e-01, 5.67456841e-01, 6.33459270e-01, 7.04189956e-01,
        5.90720117e-01, 1.21110819e-01, 3.65544826e-01, 3.92474771e-01],
       [4.13428247e-01, 2.36738130e-01, 3.33703488e-01, 9.51903313e-02,
        7.82825828e-01, 4.16873157e-01, 5.73455989e-01, 6.107

In [21]:
E = np.zeros((N,N),dtype=np.float32)

In [22]:
E

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [23]:
I = np.eye(N,N)

In [24]:
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [25]:
T = np.random.randn(N,N)

In [26]:
T

array([[ 0.72180549,  0.08938942, -0.77638881, -0.65042008,  0.95838568,
        -1.33025091, -0.10842478,  0.66574616,  0.06823751,  0.12881975,
         0.19905112, -0.74974583,  0.83866017, -0.03182955,  0.52650918,
        -0.39060906],
       [ 1.05864337,  1.68236396,  0.4269313 ,  1.57970964, -0.05106661,
         1.06494614,  1.28268266, -1.3237491 ,  1.00318497, -0.18767509,
         1.45002488, -0.27823522, -2.51910711, -2.01247681,  0.77027609,
         2.32123037],
       [ 1.52171911,  0.1931801 , -1.10878193,  1.23579389,  0.55949876,
         0.51871766,  0.04823716, -0.53478277,  0.32372894, -1.27324309,
        -0.13299567, -0.04540394,  0.5573703 , -1.56807471, -1.44692147,
        -0.3422657 ],
       [-0.13376619,  1.38696243, -1.24129196, -1.79307175,  0.9702248 ,
         0.47011058, -0.55748597,  0.93094326, -1.02479602,  1.49567339,
         0.94356165, -0.40637467, -0.90305012,  2.07392122, -0.99393572,
        -0.51848504],
       [-0.21984187,  1.0495685 , -0

In [35]:
l = [[2,3,4,5],
     [4,3,5,2],
     [1,2,3,4],
     [9,2,3,4]]

In [36]:
A = np.array(l)

In [37]:
A

array([[2, 3, 4, 5],
       [4, 3, 5, 2],
       [1, 2, 3, 4],
       [9, 2, 3, 4]])

In [45]:
A[:2,2:]

array([[4, 5],
       [5, 2]])

In [47]:
A[2:,1:3]

array([[2, 3],
       [2, 3]])

In [49]:
np.random.seed(42)

In [50]:
A = np.random.randn(N,N).astype(np.float32)

In [51]:
B = np.random.randn(N,N).astype(np.float32)

In [52]:
A

array([[ 0.49671414, -0.1382643 ,  0.64768857,  1.5230298 , -0.23415338,
        -0.23413695,  1.5792128 ,  0.7674347 ],
       [-0.46947438,  0.54256004, -0.46341768, -0.46572974,  0.24196227,
        -1.9132802 , -1.7249179 , -0.5622875 ],
       [-1.0128311 ,  0.31424734, -0.9080241 , -1.4123037 ,  1.4656488 ,
        -0.2257763 ,  0.0675282 , -1.4247482 ],
       [-0.54438275,  0.11092259, -1.1509936 ,  0.37569803, -0.6006387 ,
        -0.29169375, -0.6017066 ,  1.8522782 ],
       [-0.01349723, -1.0577109 ,  0.82254493, -1.2208437 ,  0.2088636 ,
        -1.9596701 , -1.328186  ,  0.19686124],
       [ 0.73846656,  0.17136829, -0.11564828, -0.30110368, -1.478522  ,
        -0.7198442 , -0.46063876,  1.0571222 ],
       [ 0.3436183 , -1.7630402 ,  0.32408398, -0.38508227, -0.676922  ,
         0.6116763 ,  1.0309995 ,  0.93128014],
       [-0.83921754, -0.3092124 ,  0.33126342,  0.9755451 , -0.47917423,
        -0.18565898, -1.1063349 , -1.1962066 ]], dtype=float32)

In [53]:
B

array([[ 0.8125258 ,  1.35624   , -0.07201012,  1.0035329 ,  0.361636  ,
        -0.6451197 ,  0.3613956 ,  1.5380366 ],
       [-0.03582604,  1.5646436 , -2.619745  ,  0.8219025 ,  0.08704707,
        -0.29900736,  0.09176078, -1.9875689 ],
       [-0.21967189,  0.35711256,  1.4778941 , -0.5182702 , -0.8084936 ,
        -0.501757  ,  0.9154021 ,  0.32875112],
       [-0.5297602 ,  0.51326746,  0.09707755,  0.968645  , -0.70205307,
        -0.32766214, -0.39210814, -1.4635149 ],
       [ 0.2961203 ,  0.26105526,  0.00511346, -0.23458713, -1.4153707 ,
        -0.42064533, -0.34271452, -0.80227727],
       [-0.16128571,  0.40405086,  1.8861859 ,  0.17457782,  0.2575504 ,
        -0.07444592, -1.9187713 , -0.02651387],
       [ 0.06023021,  2.463242  , -0.19236097,  0.30154735, -0.03471177,
        -1.168678  ,  1.1428229 ,  0.75193304],
       [ 0.79103196, -0.90938747,  1.4027944 , -1.401851  ,  0.5868571 ,
         2.1904557 , -0.99053633, -0.5662977 ]], dtype=float32)

In [54]:
A + B

array([[ 1.30924   ,  1.2179757 ,  0.57567847,  2.5265627 ,  0.12748264,
        -0.87925667,  1.9406084 ,  2.3054714 ],
       [-0.5053004 ,  2.1072037 , -3.0831628 ,  0.35617277,  0.32900935,
        -2.2122877 , -1.6331571 , -2.5498564 ],
       [-1.2325029 ,  0.6713599 ,  0.56987   , -1.9305739 ,  0.65715516,
        -0.72753334,  0.9829303 , -1.0959971 ],
       [-1.0741429 ,  0.62419003, -1.053916  ,  1.344343  , -1.3026917 ,
        -0.6193559 , -0.99381477,  0.3887633 ],
       [ 0.28262305, -0.79665565,  0.8276584 , -1.4554307 , -1.2065071 ,
        -2.3803153 , -1.6709006 , -0.60541606],
       [ 0.57718086,  0.5754191 ,  1.7705376 , -0.12652586, -1.2209716 ,
        -0.7942901 , -2.37941   ,  1.0306084 ],
       [ 0.40384853,  0.70020187,  0.13172302, -0.08353493, -0.7116338 ,
        -0.55700177,  2.1738224 ,  1.6832132 ],
       [-0.04818559, -1.2185998 ,  1.7340578 , -0.42630595,  0.10768285,
         2.0047967 , -2.0968714 , -1.7625043 ]], dtype=float32)

In [55]:
A @ B

array([[ 0.13003409,  4.506706  ,  1.7614669 ,  0.93885934, -0.7586366 ,
        -1.1517532 ,  1.7366177 , -0.03034459],
       [-0.22081776, -4.639793  , -6.182188  , -0.35883135, -0.52625316,
         1.3506262 ,  1.8124365 , -2.393184  ],
       [-0.5390912 , -0.17773671, -4.6593604 , -0.02113786, -1.5843308 ,
        -2.3216758 ,  0.80472314, -0.7262079 ],
       [ 0.9056672 , -4.224207  ,  0.24488774, -2.1827772 ,  2.3625076 ,
         5.8073483 , -3.1443472 , -2.9977484 ],
       [ 0.9466332 , -6.1940727 ,  0.7054357 , -3.5593376 , -0.5435771 ,
         2.353747  ,  3.1054263 ,  2.912852  ],
       [ 1.2655544 , -1.6990061 , -0.496051  , -0.74946094,  3.1304946 ,
         3.1584885 ,  0.609185  ,  1.4580877 ],
       [ 0.9748353 , -0.6112751 ,  7.293895  , -2.3742247 ,  1.6054993 ,
         1.3432811 , -0.27582753,  5.477501  ],
       [-2.3852038 , -2.8404357 , -0.36308816,  1.1002355 , -1.3163229 ,
        -0.96391463,  0.03005525, -1.7601155 ]], dtype=float32)

In [56]:
np.dot(A,B)

array([[ 0.13003409,  4.506706  ,  1.7614669 ,  0.93885934, -0.7586366 ,
        -1.1517532 ,  1.7366177 , -0.03034459],
       [-0.22081776, -4.639793  , -6.182188  , -0.35883135, -0.52625316,
         1.3506262 ,  1.8124365 , -2.393184  ],
       [-0.5390912 , -0.17773671, -4.6593604 , -0.02113786, -1.5843308 ,
        -2.3216758 ,  0.80472314, -0.7262079 ],
       [ 0.9056672 , -4.224207  ,  0.24488774, -2.1827772 ,  2.3625076 ,
         5.8073483 , -3.1443472 , -2.9977484 ],
       [ 0.9466332 , -6.1940727 ,  0.7054357 , -3.5593376 , -0.5435771 ,
         2.353747  ,  3.1054263 ,  2.912852  ],
       [ 1.2655544 , -1.6990061 , -0.496051  , -0.74946094,  3.1304946 ,
         3.1584885 ,  0.609185  ,  1.4580877 ],
       [ 0.9748353 , -0.6112751 ,  7.293895  , -2.3742247 ,  1.6054993 ,
         1.3432811 , -0.27582753,  5.477501  ],
       [-2.3852038 , -2.8404357 , -0.36308816,  1.1002355 , -1.3163229 ,
        -0.96391463,  0.03005525, -1.7601155 ]], dtype=float32)

In [59]:
N

8

In [61]:
A.size

64

In [63]:
A.shape

(8, 8)

In [64]:
A.ndim

2

In [65]:
d = [[2,3,4,5,5],
    [9,9,2,4,5]]

In [66]:
dnp = np.array(d)

In [67]:
dnp

array([[2, 3, 4, 5, 5],
       [9, 9, 2, 4, 5]])

In [68]:
dnp.T

array([[2, 9],
       [3, 9],
       [4, 2],
       [5, 4],
       [5, 5]])