In [75]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [76]:
df = pd.read_csv(r"C:\Users\felip\Documents\ML_COURSE_ASSIGMENTS\network_raw_data.csv",index_col=0)

In [77]:
df.head()

file  attribrandomize  color  attribwrangle polyreduce::2.0  normal  \
0  file  attribrandomize  color  attribwrangle      polyreduce  normal   
1  file              NaN  color  attribwrangle      polyreduce  normal   
2  file  attribrandomize  color  attribwrangle      polyreduce  normal   
3  file              NaN  color  attribwrangle      polyreduce  normal   
4  file  attribrandomize  color  attribwrangle      polyreduce  normal   

  attribnoise::2.0 polywire groupcreate xform attribblur crease groupdelete  \
0              NaN      NaN         NaN   NaN        NaN    NaN         NaN   
1              NaN      NaN         NaN   NaN        NaN    NaN         NaN   
2              NaN      NaN         NaN   NaN        NaN    NaN         NaN   
3              NaN      NaN         NaN   NaN        NaN    NaN         NaN   
4              NaN      NaN         NaN   NaN        NaN    NaN         NaN   

  attribexpression texture attribpaint          target  
0              NaN     NaN         NaN  filecache::2.0  
1              NaN     NaN         NaN  filecache::2.0  
2              NaN     NaN         NaN  filecache::2.0  
3              NaN     NaN         NaN  filecache::2.0  
4              NaN     NaN         NaN  filecache::2.0

In [78]:
df.tail()

file attribrandomize color attribwrangle polyreduce::2.0  normal  \
251  file             NaN   NaN           NaN             NaN  normal   
252  file             NaN   NaN           NaN             NaN  normal   
253  file             NaN   NaN           NaN      polyreduce  normal   
254  file             NaN   NaN           NaN             NaN  normal   
255  file             NaN   NaN           NaN      polyreduce  normal   

    attribnoise::2.0 polywire groupcreate      xform  attribblur  crease  \
251              NaN      NaN         NaN  transform  attribblur  crease   
252              NaN      NaN         NaN  transform  attribblur  crease   
253              NaN      NaN         NaN        NaN  attribblur  crease   
254              NaN      NaN         NaN  transform  attribblur  crease   
255              NaN      NaN         NaN        NaN  attribblur  crease   

     groupdelete  attribexpression    texture  attribpaint   target  
251          NaN  attribexpression  uvtexture  attribpaint  rop_fbx  
252          NaN  attribexpression  uvtexture  attribpaint  rop_fbx  
253  groupdelete               NaN        NaN          NaN    stash  
254          NaN  attribexpression  uvtexture  attribpaint  rop_fbx  
255  groupdelete               NaN        NaN          NaN    stash

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 256 entries, 0 to 255
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   file              256 non-null    object
 1   attribrandomize   32 non-null     object
 2   color             64 non-null     object
 3   attribwrangle     136 non-null    object
 4   polyreduce::2.0   128 non-null    object
 5   normal            176 non-null    object
 6   attribnoise::2.0  80 non-null     object
 7   polywire          80 non-null     object
 8   groupcreate       80 non-null     object
 9   xform             64 non-null     object
 10  attribblur        96 non-null     object
 11  crease            104 non-null    object
 12  groupdelete       64 non-null     object
 13  attribexpression  48 non-null     object
 14  texture           48 non-null     object
 15  attribpaint       48 non-null     object
 16  target            256 non-null    object
dtypes: object(17)
memory 

In [80]:
object_columns = df.select_dtypes(include=['object']).columns.tolist()

In [81]:
object_columns

['file',
 'attribrandomize',
 'color',
 'attribwrangle',
 'polyreduce::2.0',
 'normal',
 'attribnoise::2.0',
 'polywire',
 'groupcreate',
 'xform',
 'attribblur',
 'crease',
 'groupdelete',
 'attribexpression',
 'texture',
 'attribpaint',
 'target']

In [82]:
df['target'].value_counts()

target
rop_alembic       80
filecache::2.0    64
stash             64
rop_fbx           48
Name: count, dtype: int64

In [84]:
df = set_col_mapping(df, 'object')
df

[]


file  attribrandomize  color  attribwrangle  polyreduce::2.0  normal  \
0       0              0.0    0.0            0.0              0.0     0.0   
1       0              NaN    0.0            0.0              0.0     0.0   
2       0              0.0    0.0            0.0              0.0     0.0   
3       0              NaN    0.0            0.0              0.0     0.0   
4       0              0.0    0.0            0.0              0.0     0.0   
..    ...              ...    ...            ...              ...     ...   
251     0              NaN    NaN            NaN              NaN     0.0   
252     0              NaN    NaN            NaN              NaN     0.0   
253     0              NaN    NaN            NaN              0.0     0.0   
254     0              NaN    NaN            NaN              NaN     0.0   
255     0              NaN    NaN            NaN              0.0     0.0   

     attribnoise::2.0  polywire  groupcreate  xform  attribblur  crease  \
0                 NaN       NaN          NaN    NaN         NaN     NaN   
1                 NaN       NaN          NaN    NaN         NaN     NaN   
2                 NaN       NaN          NaN    NaN         NaN     NaN   
3                 NaN       NaN          NaN    NaN         NaN     NaN   
4                 NaN       NaN          NaN    NaN         NaN     NaN   
..                ...       ...          ...    ...         ...     ...   
251               NaN       NaN          NaN    0.0         0.0     0.0   
252               NaN       NaN          NaN    0.0         0.0     0.0   
253               NaN       NaN          NaN    NaN         0.0     0.0   
254               NaN       NaN          NaN    0.0         0.0     0.0   
255               NaN       NaN          NaN    NaN         0.0     0.0   

     groupdelete  attribexpression  texture  attribpaint  target  
0            NaN               NaN      NaN          NaN       1  
1            NaN               NaN      NaN          NaN       1  
2            NaN               NaN      NaN          NaN       1  
3            NaN               NaN      NaN          NaN       1  
4            NaN               NaN      NaN          NaN       1  
..           ...               ...      ...          ...     ...  
251          NaN               0.0      0.0          0.0       3  
252          NaN               0.0      0.0          0.0       3  
253          0.0               NaN      NaN          NaN       2  
254          NaN               0.0      0.0          0.0       3  
255          0.0               NaN      NaN          NaN       2  

[256 rows x 17 columns]

In [61]:
columns_to_remap = df.columns[:-1]
columns_to_remap

Index(['file', 'attribrandomize', 'color', 'attribwrangle', 'polyreduce::2.0',
       'normal', 'attribnoise::2.0', 'polywire', 'groupcreate', 'xform',
       'attribblur', 'crease', 'groupdelete', 'attribexpression', 'texture',
       'attribpaint'],
      dtype='object')

In [62]:
for column in columns_to_remap:
    df[column] = df[column].notna().astype(int)

In [64]:
df.head(20)

file  attribrandomize  color  attribwrangle  polyreduce::2.0  normal  \
0      1                1      1              1                1       1   
1      1                0      1              1                1       1   
2      1                1      1              1                1       1   
3      1                0      1              1                1       1   
4      1                1      1              1                1       1   
5      1                0      1              1                1       1   
6      1                1      1              1                1       1   
7      1                0      1              1                1       1   
8      1                0      0              1                0       0   
9      1                0      0              1                0       0   
10     1                0      0              1                0       0   
11     1                0      0              1                0       0   
12     1                0      0              1                0       0   
13     1                0      0              1                0       0   
14     1                0      0              1                0       0   
15     1                0      0              1                0       0   
16     1                0      0              0                1       1   
17     1                0      0              0                1       1   
18     1                0      0              0                1       1   
19     1                0      0              0                1       1   

    attribnoise::2.0  polywire  groupcreate  xform  attribblur  crease  \
0                  0         0            0      0           0       0   
1                  0         0            0      0           0       0   
2                  0         0            0      0           0       0   
3                  0         0            0      0           0       0   
4                  0         0            0      0           0       0   
5                  0         0            0      0           0       0   
6                  0         0            0      0           0       0   
7                  0         0            0      0           0       0   
8                  1         1            1      1           0       0   
9                  1         1            1      0           0       0   
10                 1         1            1      1           0       0   
11                 1         1            1      0           0       0   
12                 1         1            1      1           0       0   
13                 1         1            1      0           0       0   
14                 1         1            1      1           0       0   
15                 1         1            1      0           0       0   
16                 0         0            0      0           1       1   
17                 0         0            0      0           1       1   
18                 0         0            0      0           1       1   
19                 0         0            0      0           1       1   

    groupdelete  attribexpression  texture  attribpaint          target  
0             0                 0        0            0  filecache::2.0  
1             0                 0        0            0  filecache::2.0  
2             0                 0        0            0  filecache::2.0  
3             0                 0        0            0  filecache::2.0  
4             0                 0        0            0  filecache::2.0  
5             0                 0        0            0  filecache::2.0  
6             0                 0        0            0  filecache::2.0  
7             0                 0        0            0  filecache::2.0  
8             0                 0        0            0     rop_alembic  
9             0                 0        0            0     rop_alembic  
10            0                 0     

In [65]:
class_names = {"rop_alembic":0,
    "filecache::2.0": 1, 
    "stash": 2,
    "rop_fbx": 3}

In [66]:
X = df.drop('target', axis=1)
y = df['target'].map(class_names)

In [67]:
y

0      1
1      1
2      1
3      1
4      1
      ..
251    3
252    3
253    2
254    3
255    2
Name: target, Length: 256, dtype: int64

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [69]:
svm_model = SVC()
svm_model.fit(X_train, y_train)

SVC()

In [70]:
y_pred = svm_model.predict(X_test)

In [71]:
print(confusion_matrix(y_test, y_pred))
print("------------------------------")
print(classification_report(y_test, y_pred))

[[13  0  0  0]
 [ 0 12  0  0]
 [ 0  0 17  0]
 [ 0  0  0 10]]
------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        17
           3       1.00      1.00      1.00        10

    accuracy                           1.00        52
   macro avg       1.00      1.00      1.00        52
weighted avg       1.00      1.00      1.00        52



In [72]:
import pickle

In [74]:
with open("svm_houdini_model.pkl", "wb") as f:
    pickle.dump(svm_model, f)

In [85]:
X_test

file  attribrandomize  color  attribwrangle  polyreduce::2.0  normal  \
228     1                0      0              0                1       1   
6       1                1      1              1                1       1   
79      1                0      0              1                0       0   
206     1                0      0              1                0       0   
117     1                0      0              0                1       1   
185     1                0      0              0                0       1   
242     1                0      0              1                0       0   
167     1                0      0              0                1       1   
9       1                0      0              1                0       0   
30      1                0      0              1                0       0   
180     1                0      0              0                1       1   
222     1                0      0              1                0       0   
230     1                0      0              0                1       1   
217     1                0      0              0                0       1   
136     1                0      0              1                0       0   
68      1                1      1              0                1       1   
199     1                0      1              1                1       1   
15      1                0      0              1                0       0   
96      1                0      1              1                1       1   
24      1                0      0              0                0       1   
235     1                0      0              0                0       1   
19      1                0      0              0                1       1   
120     1                0      0              0                1       1   
152     1                0      0              0                0       1   
33      1                0      1              1                1       1   
124     1                0      0              0                0       1   
253     1                0      0              0                1       1   
208     1                0      0              0                1       1   
10      1                0      0              1                0       0   
164     1                0      0              0                1       1   
184     1                0      0              0                1       1   
97      1                0      1              1                1       1   
148     1                1      1              1                1       1   
190     1                0      0              0                0       1   
223     1                0      0              1                0       0   
25      1                0      0              0                0       1   
86      1                1      1              1                1       1   
18      1                0      0              0                1       1   
75      1                0      0              1                0       0   
137     1                0      0              1                0       0   
196     1                1      1              0                1       1   
176     1                0      0              0                1       1   
239     1                0      0              0                0       1   
181     1                0      0              0                1       1   
45      1                0      0              0                0       1   
66      1                1      1              0                1       1   
16      1                0      0              0                1       1   
67      1                0      1              1                1       1   
215     1                1      1              1                1       1   
201     1                0      0              1                0       0   
177     1                0      0              0                1       1   
3